site_name: Docs2KG by AI4WA
site_url: https://docs2kg.ai4wa.com
theme:
  name: material
  logo: images/AI4WA.png
  favicon: images/favicon.ico
  features:
    - search.suggest
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/AI4WA/Docs2KG
plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
            show_source_link: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AI4WA/Docs2KG
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ai4wa
    - icon: fontawesome/solid/box-open
      link: https://pypi.org/project/Docs2KG/
  analytics:
    provider: google
    property: G-3KY1SY1J0Q